const sampleListings = [
  {
      title: "Hillside Cottage",
      description: "Escape to this charming hillside retreat with breathtaking valley views. Perfect for nature lovers seeking peace and tranquility.",
      price: 1300,
      location: "Murree",
      country: "Pakistan",
  },
  {
      title: "Heritage Guesthouse",
      description: "Stay in a beautifully restored traditional home with antique furnishings. Experience the rich history and culture of the region.",
      price: 900,
      location: "Shigar",
      country: "Pakistan",
  },
  {
      title: "Luxury Safari Camp",
      description: "Enjoy a premium glamping experience in the heart of the desert. Watch the sunset over the dunes and gaze at the stars at night.",
      price: 2600,
      location: "Cholistan Desert",
      country: "Pakistan",
  },
  {
      title: "Secluded River Cabin",
      description: "Nestled by the river, this cozy wooden cabin is perfect for a romantic getaway. Enjoy fishing, bonfires, and scenic walks.",
      price: 1400,
      location: "Neelum Valley",
      country: "Pakistan",
  },
  {
      title: "Treehouse Hideaway",
      description: "A unique stay high up in the trees with stunning jungle views. A peaceful escape for adventurers and dreamers alike.",
      price: 1700,
      location: "Galiyat",
      country: "Pakistan",
  },
  {
      title: "Skyline Apartment",
      description: "A modern high-rise apartment with floor-to-ceiling windows. Unwind in style while enjoying a spectacular cityscape view.",
      price: 3200,
      location: "New York City",
      country: "USA",
  },
  {
      title: "Garden Villa",
      description: "Surrounded by lush gardens, this villa offers a serene environment with a private pool and luxurious interiors.",
      price: 2900,
      location: "Bali",
      country: "Indonesia",
  },
  {
      title: "Bohemian Artist Loft",
      description: "A creative space in the heart of the city with artistic décor and a vibrant atmosphere. Ideal for artists and free spirits.",
      price: 1600,
      location: "Paris",
      country: "France",
  },
  {
      title: "Winter Wonderland Chalet",
      description: "A cozy wooden chalet with a fireplace, nestled in snowy mountains. Perfect for a magical winter getaway.",
      price: 1900,
      location: "Swiss Alps",
      country: "Switzerland",
  },
  {
      title: "Floating Houseboat",
      description: "Experience the charm of a floating stay with lake views and traditional wooden interiors. A unique and peaceful retreat.",
      price: 2100,
      location: "Amsterdam",
      country: "Netherlands",
  },
  {
      title: "Seaside Bungalow",
      description: "Wake up to the sound of waves in this beachfront paradise. A perfect getaway for ocean lovers and surfers.",
      price: 2500,
      location: "Maui",
      country: "USA",
  },
  {
      title: "Tokyo Capsule Hotel",
      description: "A futuristic and compact stay in the heart of Tokyo. Ideal for solo travelers looking for a unique experience.",
      price: 600,
      location: "Tokyo",
      country: "Japan",
  },
  {
      title: "Historic Castle Stay",
      description: "Live like royalty in this centuries-old castle with grand halls, antique décor, and breathtaking views.",
      price: 5000,
      location: "Edinburgh",
      country: "Scotland",
  },
  {
      title: "Tropical Jungle Treehouse",
      description: "Stay above the treetops in a luxurious treehouse surrounded by lush rainforest and exotic wildlife.",
      price: 2700,
      location: "Costa Rica",
      country: "Costa Rica",
  },
  {
      title: "Desert Dome",
      description: "Sleep under a blanket of stars in a stylish dome in the heart of the desert. Unplug and reconnect with nature.",
      price: 2300,
      location: "Dubai",
      country: "UAE",
  },
];

export default { data: sampleListings };